name: pennApps-crime-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - requests=2.31.0
  - pandas=2.1.1
  - pip
  - pip:
    - Flask-CORS==4.0.0
    - python-dotenv==1.0.0
    - geopy==2.4.0
    - redis==5.0.0
    - APScheduler==3.10.4
    - gunicorn==21.2.0
